### PR TITLE
Add xgettext wrapper

### PR DESCRIPTION
**Pull request by y5nw**
This PR adds a simple `xgettext` wrapper that (among other things) adds Luanti-related keywords to be recognized by `xgettext`.

### CODE REVIEW

**Review by appgurueu — APPROVED** [review]

**Comment by Wuzzy2** [comment]
IMHO it makes sense to include the msgid-bugs email address and project-name and project-version as (optional) arguments. And maybe also `--add-comments` for comments directed at translators (important to explain obscure strings).

**Comment by rubenwardy** [comment]
Any idea how you might approach #2 with this?

**Comment by y5nw** [comment]
> IMHO it makes sense to include the msgid-bugs email address and project-name and project-version as (optional) arguments. And maybe also `--add-comments` for comments directed at translators (important to explain obscure strings).

The script passes user-supplied arguments directly to `xgettext` so this is already possible. I don't think these options have a (simple to implement) sensible default that the script can provide otherwise.

> Any idea how you might approach #2 with this?

I would suggest using a different script that collects entries from `mod.conf` into a Lua file. It seems like Luanti takes this approach to make settings translatable: https://github.com/minetest/minetest/blob/master/builtin/mainmenu/settings/generate_from_settingtypes.lua

**Comment by appgurueu** [comment]
Merged as-is, further improvements can be made later on.

**Pull request merged**
